apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
  spec:
      containers:
        - name: auth-service
          image: youruniqueacrname.azurecr.io/auth-service:v1 # <-- IMPORTANT: REPLACE with your ACR name
          ports:
            - containerPort: 5001
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: mern-app-secrets
                  key: MONGO_URI
            - name: PORT
              value: "5001"
