apiVersion: v1
kind: Service
metadata:
  name: client-service
spec:
  type: LoadBalancer # Exposes the service externally
  selector:
    app: client
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
